name: Deploy Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Verify Node.js Version
        run: node -v

      - name: Install Dependencies
        run: npm install

      - name: Build Server
        run: npm run build

      - name: Create Environment File
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI}}" > .env
          echo "EMAIL_HOST=${{ secrets.EMAIL_HOST}}" >> .env
          echo "EMAIL_PORT=${{ secrets.EMAIL_PORT}}" >> .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD}}" >> .env
          echo "SEND_EMAILS=${{ secrets.SEND_EMAILS }}" >> .env
          echo "FROM_EMAIL=${{ secrets.FROM_EMAIL }}" >> .env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "LOG_FREQUENCY=${{ secrets.LOG_FREQUENCY }}" >> .env
          echo "LOG_SIZE=${{ secrets.LOG_SIZE }}" >> .env
          echo "LOG_FILE_ON=${{ secrets.LOG_FILE_ON }}" >> .env
          echo "LOG_PATH=${{ secrets.LOG_PATH }}" >> .env
          echo "PORT=${{ secrets.SERVER_PORT }}" >> .env
          echo "PROTOCOL=${{ secrets.PROTOCOL }}" >> .env
          echo "HOST=${{ secrets.SERVER_HOST }}" >> .env

      - name: Setup SSH
        env:
          PRIVATE_KEY: ${{ secrets.DIGITAL_OCEAN_PRIVATE_KEY }}
        run: |
          echo "${PRIVATE_KEY}" | sed 's/\r$//' > private_key
          chmod 600 private_key

      - name: Ensure Target Directory Exists
        env:
          HOST: ${{ secrets.DIGITAL_OCEAN_IP }}
          USER: ${{ secrets.DIGITAL_OCEAN_USER }}
          PORT: ${{ secrets.PORT }}
        run: |
          ssh -i private_key -p $PORT -o StrictHostKeyChecking=no $USER@$HOST "
            mkdir -p /var/www/s4yt/s4yt-api/build
          "

      - name: Deploy Server Files
        env:
          HOST: ${{ secrets.DIGITAL_OCEAN_IP }}
          USER: ${{ secrets.DIGITAL_OCEAN_USER }}
          PORT: ${{ secrets.PORT }}
        run: |
          rsync -avz --delete \
            -e "ssh -i private_key -p $PORT -o StrictHostKeyChecking=no" \
            build/ \
            package.json \
            package-lock.json \
            .env \
            $USER@$HOST:/var/www/s4yt/s4yt-api/

      - name: Restart Server
        env:
          HOST: ${{ secrets.DIGITAL_OCEAN_IP }}
          USER: ${{ secrets.DIGITAL_OCEAN_USER }}
          PORT: ${{ secrets.PORT }}
        run: |
          ssh -i private_key -p $PORT -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd /var/www/s4yt/s4yt-api/

            npm install --omit=dev

            pm2 restart s4yt-api || pm2 start server.cjs --name s4yt-api

            pm2 save
          EOF